
package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-12-04T15:28:18.698+09:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "NoSuchNameException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class NoSuchNameExceptionResponse extends Exception {
    
    private org.fosstrak.epcis.model.NoSuchNameException noSuchNameException;

    public NoSuchNameExceptionResponse() {
        super();
    }
    
    public NoSuchNameExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchNameExceptionResponse(String message, org.fosstrak.epcis.model.NoSuchNameException noSuchNameException) {
        super(message);
        this.noSuchNameException = noSuchNameException;
    }

    public NoSuchNameExceptionResponse(String message, org.fosstrak.epcis.model.NoSuchNameException noSuchNameException, Throwable cause) {
        super(message, cause);
        this.noSuchNameException = noSuchNameException;
    }

    public org.fosstrak.epcis.model.NoSuchNameException getFaultInfo() {
        return this.noSuchNameException;
    }
}
