
package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-12-04T15:28:18.717+09:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ValidationExceptionResponse extends Exception {
    
    private org.fosstrak.epcis.model.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }
    
    public ValidationExceptionResponse(String message) {
        super(message);
    }
    
    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.fosstrak.epcis.model.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message, org.fosstrak.epcis.model.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.fosstrak.epcis.model.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
